// Generated by Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if defined(__has_attribute) && __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if defined(__has_attribute) && __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import Dispatch;
@import Foundation;
@import CoreGraphics;
#endif

#import <xLib6000/xLib6000.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class Radio;

SWIFT_CLASS("_TtC8xLib60009Amplifier")
@interface Amplifier : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
/// Initialize an Amplifier
/// \param id an Xvtr Id
///
/// \param radio parent Radio class
///
/// \param queue Xvtr Concurrent queue
///
- (nonnull instancetype)initWithRadio:(Radio * _Nonnull)radio id:(NSString * _Nonnull)id queue:(dispatch_queue_t _Nonnull)queue OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface Amplifier (SWIFT_EXTENSION(xLib6000))
@end


@interface Amplifier (SWIFT_EXTENSION(xLib6000))
@property (nonatomic, copy) NSString * _Nonnull ant;
@property (nonatomic, copy) NSString * _Nonnull ip;
@property (nonatomic, copy) NSString * _Nonnull model;
@property (nonatomic) NSInteger port;
@property (nonatomic, copy) NSString * _Nonnull serialNumber;
@end


SWIFT_CLASS("_TtC8xLib60003Atu")
@interface Atu : NSObject
- (nonnull instancetype)initWithRadio:(Radio * _Nonnull)radio queue:(dispatch_queue_t _Nonnull)queue OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface Atu (SWIFT_EXTENSION(xLib6000))
@property (nonatomic) BOOL memoriesEnabled;
@property (nonatomic) BOOL enabled;
@end


@interface Atu (SWIFT_EXTENSION(xLib6000))
@property (nonatomic, readonly) BOOL status;
@property (nonatomic, readonly) BOOL usingMemories;
@end


SWIFT_CLASS("_TtC8xLib600011AudioStream")
@interface AudioStream : NSObject
@property (nonatomic, readonly) NSInteger rxLostPacketCount;
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface AudioStream (SWIFT_EXTENSION(xLib6000))
@property (nonatomic) NSInteger rxGain;
@end

@class Slice;

@interface AudioStream (SWIFT_EXTENSION(xLib6000))
@property (nonatomic) NSInteger daxChannel;
@property (nonatomic) NSInteger daxClients;
@property (nonatomic, readonly) BOOL inUse;
@property (nonatomic, copy) NSString * _Nonnull ip;
@property (nonatomic) NSInteger port;
@property (nonatomic, strong) Slice * _Nullable slice;
@end


SWIFT_CLASS("_TtC8xLib60003Cwx")
@interface Cwx : NSObject
@property (nonatomic, copy) void (^ _Nullable messageQueuedEventHandler)(NSInteger, NSInteger);
@property (nonatomic, copy) void (^ _Nullable charSentEventHandler)(NSInteger);
@property (nonatomic, copy) void (^ _Nullable eraseSentEventHandler)(NSInteger, NSInteger);
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface Cwx (SWIFT_EXTENSION(xLib6000))
@end


@interface Cwx (SWIFT_EXTENSION(xLib6000))
/// Clear the character buffer
- (void)clearBuffer;
/// Erase “n” characters
/// \param numberOfChars number of characters to erase
///
- (void)eraseWithNumberOfChars:(NSInteger)numberOfChars;
/// Save the specified Cwx Macro and tell the Radio (hardware)
/// \code
/// NOTE:
///     Macros are numbered 0..<kMaxNumberOfMacros internally
///     Macros are numbered 1...kMaxNumberOfMacros in commands
///
/// \endcode\param index the index of the macro
///
/// \param msg the text of the macro
///
///
/// returns:
/// true if found, false otherwise
- (BOOL)saveMacroWithIndex:(NSInteger)index msg:(NSString * _Nonnull)msg SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic) NSInteger breakInDelay;
@property (nonatomic) BOOL qskEnabled;
@property (nonatomic) NSInteger wpm;
@end


SWIFT_CLASS("_TtC8xLib60009Equalizer")
@interface Equalizer : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface Equalizer (SWIFT_EXTENSION(xLib6000))
@end


@interface Equalizer (SWIFT_EXTENSION(xLib6000))
@property (nonatomic) BOOL eqEnabled;
@property (nonatomic) NSInteger level63Hz;
@property (nonatomic) NSInteger level125Hz;
@property (nonatomic) NSInteger level250Hz;
@property (nonatomic) NSInteger level500Hz;
@property (nonatomic) NSInteger level1000Hz;
@property (nonatomic) NSInteger level2000Hz;
@property (nonatomic) NSInteger level4000Hz;
@property (nonatomic) NSInteger level8000Hz;
@end


SWIFT_CLASS("_TtC8xLib60003Gps")
@interface Gps : NSObject
- (nonnull instancetype)initWithRadio:(Radio * _Nonnull)radio queue:(dispatch_queue_t _Nonnull)queue OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface Gps (SWIFT_EXTENSION(xLib6000))
@property (nonatomic, readonly, copy) NSString * _Nonnull altitude;
@property (nonatomic, readonly) double frequencyError;
@property (nonatomic, readonly, copy) NSString * _Nonnull grid;
@property (nonatomic, readonly, copy) NSString * _Nonnull latitude;
@property (nonatomic, readonly, copy) NSString * _Nonnull longitude;
@property (nonatomic, readonly, copy) NSString * _Nonnull speed;
@property (nonatomic, readonly) BOOL status;
@property (nonatomic, readonly, copy) NSString * _Nonnull time;
@property (nonatomic, readonly) double track;
@property (nonatomic, readonly) BOOL tracked;
@property (nonatomic, readonly) BOOL visible;
@end


SWIFT_CLASS("_TtC8xLib60009Interlock")
@interface Interlock : NSObject
- (nonnull instancetype)initWithRadio:(Radio * _Nonnull)radio queue:(dispatch_queue_t _Nonnull)queue OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface Interlock (SWIFT_EXTENSION(xLib6000))
@property (nonatomic) BOOL accTxEnabled;
@property (nonatomic) NSInteger accTxDelay;
@property (nonatomic) BOOL accTxReqEnabled;
@property (nonatomic) BOOL accTxReqPolarity;
@property (nonatomic) BOOL rcaTxReqEnabled;
@property (nonatomic) BOOL rcaTxReqPolarity;
@property (nonatomic) NSInteger timeout;
@property (nonatomic) BOOL tx1Enabled;
@property (nonatomic) NSInteger tx1Delay;
@property (nonatomic) BOOL tx2Enabled;
@property (nonatomic) NSInteger tx2Delay;
@property (nonatomic) BOOL tx3Enabled;
@property (nonatomic) NSInteger tx3Delay;
@end


@interface Interlock (SWIFT_EXTENSION(xLib6000))
@property (nonatomic, readonly, copy) NSString * _Nonnull reason;
@property (nonatomic, readonly, copy) NSString * _Nonnull source;
@property (nonatomic, readonly, copy) NSString * _Nonnull state;
@property (nonatomic, readonly) BOOL txAllowed;
@property (nonatomic, readonly) NSInteger txDelay;
@end


SWIFT_CLASS("_TtC8xLib60008IqStream")
@interface IqStream : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly) NSInteger rxLostPacketCount;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface IqStream (SWIFT_EXTENSION(xLib6000))
@property (nonatomic) NSInteger rate;
@end


@interface IqStream (SWIFT_EXTENSION(xLib6000))
@property (nonatomic, readonly) NSInteger available;
@property (nonatomic, readonly) NSInteger capacity;
@property (nonatomic, readonly) NSInteger daxIqChannel;
@property (nonatomic, readonly) BOOL inUse;
@property (nonatomic, readonly, copy) NSString * _Nonnull ip;
@property (nonatomic, readonly) NSInteger port;
@property (nonatomic, readonly, copy) NSString * _Nullable pan;
@property (nonatomic, readonly) BOOL streaming;
@end


SWIFT_CLASS("_TtC8xLib60006Memory")
@interface Memory : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
- (void)select;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface Memory (SWIFT_EXTENSION(xLib6000))
@property (nonatomic) NSInteger digitalLowerOffset;
@property (nonatomic) NSInteger digitalUpperOffset;
@property (nonatomic) NSInteger filterHigh;
@property (nonatomic) NSInteger filterLow;
@property (nonatomic) NSInteger frequency;
@property (nonatomic, copy) NSString * _Nonnull group;
@property (nonatomic, copy) NSString * _Nonnull mode;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) NSInteger offset;
@property (nonatomic, copy) NSString * _Nonnull offsetDirection;
@property (nonatomic, copy) NSString * _Nonnull owner;
@property (nonatomic) NSInteger rfPower;
@property (nonatomic) NSInteger rttyMark;
@property (nonatomic) NSInteger rttyShift;
@property (nonatomic) BOOL squelchEnabled;
@property (nonatomic) NSInteger squelchLevel;
@property (nonatomic) NSInteger step;
@property (nonatomic, copy) NSString * _Nonnull toneMode;
@property (nonatomic) NSInteger toneValue;
@end


@interface Memory (SWIFT_EXTENSION(xLib6000))
@end


SWIFT_CLASS("_TtC8xLib600014MicAudioStream")
@interface MicAudioStream : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic) NSInteger rxLostPacketCount;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface MicAudioStream (SWIFT_EXTENSION(xLib6000))
@end


@interface MicAudioStream (SWIFT_EXTENSION(xLib6000))
@property (nonatomic, readonly) BOOL inUse;
@property (nonatomic, copy) NSString * _Nonnull ip;
@property (nonatomic) NSInteger port;
@property (nonatomic) NSInteger micGain;
@end


@interface NSNotificationCenter (SWIFT_EXTENSION(xLib6000))
/// post a Notification by Name
/// \param notification Notification Name
///
/// \param object associated object
///
+ (void)post:(NSString * _Nonnull)name object:(id _Nullable)object;
/// setup a Notification Observer by Name
/// \param observer the object receiving Notifications
///
/// \param selector a Selector to receive the Notification
///
/// \param type Notification name
///
/// \param object associated object (if any)
///
+ (void)makeObserver:(id _Nonnull)observer with:(SEL _Nonnull)selector of:(NSString * _Nonnull)name object:(id _Nullable)object;
@end


SWIFT_CLASS("_TtC8xLib60004Opus")
@interface Opus : NSObject
/// Send Opus encoded TX audio to the Radio (hardware)
/// \param buffer array of encoded audio samples
///
/// \param samples number of samples to be sent
///
///
/// returns:
/// success / failure
- (void)sendOpusTxAudioWithBuffer:(NSArray<NSNumber *> * _Nonnull)buffer samples:(NSInteger)samples;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface Opus (SWIFT_EXTENSION(xLib6000))
@property (nonatomic) BOOL remoteRxOn;
@property (nonatomic) BOOL remoteTxOn;
@end


@interface Opus (SWIFT_EXTENSION(xLib6000))
@property (nonatomic) BOOL rxStreamStopped;
@end


SWIFT_CLASS("_TtC8xLib600010Panadapter")
@interface Panadapter : NSObject
@property (nonatomic, readonly, strong) Radio * _Nullable radio;
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly) NSInteger lastFrameIndex;
@property (nonatomic, readonly) NSInteger droppedPackets;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface Panadapter (SWIFT_EXTENSION(xLib6000))
- (void)requestRfGainInfo;
@property (nonatomic) NSInteger average;
@property (nonatomic, copy) NSString * _Nonnull band;
@property (nonatomic) NSInteger bandwidth;
@property (nonatomic) NSInteger center;
@property (nonatomic) NSInteger daxIqChannel;
@property (nonatomic) NSInteger fps;
@property (nonatomic) BOOL loopAEnabled;
@property (nonatomic) BOOL loopBEnabled;
@property (nonatomic) CGFloat maxDbm;
@property (nonatomic) CGFloat minDbm;
@property (nonatomic) CGSize panDimensions;
@property (nonatomic) NSInteger rfGain;
@property (nonatomic, copy) NSString * _Nonnull rxAnt;
@property (nonatomic) BOOL weightedAverageEnabled;
@property (nonatomic) BOOL wnbEnabled;
@property (nonatomic) NSInteger wnbLevel;
@end


@interface Panadapter (SWIFT_EXTENSION(xLib6000))
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull antList;
@property (nonatomic, readonly) NSInteger maxBw;
@property (nonatomic, readonly) NSInteger minBw;
@property (nonatomic, readonly, copy) NSString * _Nonnull preamp;
@property (nonatomic, readonly) NSInteger rfGainHigh;
@property (nonatomic, readonly) NSInteger rfGainLow;
@property (nonatomic, readonly) NSInteger rfGainStep;
@property (nonatomic, readonly, copy) NSString * _Nonnull rfGainValues;
@property (nonatomic, readonly, copy) NSString * _Nonnull waterfallId;
@property (nonatomic, readonly) BOOL wide;
@property (nonatomic, readonly) BOOL wnbUpdating;
@property (nonatomic, readonly, copy) NSString * _Nonnull xvtrLabel;
@end


SWIFT_CLASS("_TtC8xLib60007Profile")
@interface Profile : NSObject
- (nonnull instancetype)initWithRadio:(Radio * _Nonnull)radio radioQ:(dispatch_queue_t _Nonnull)radioQ objectQ:(dispatch_queue_t _Nonnull)objectQ OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface Profile (SWIFT_EXTENSION(xLib6000))
@property (nonatomic, copy) NSString * _Nonnull currentGlobalProfile;
@property (nonatomic, copy) NSString * _Nonnull currentMicProfile;
@property (nonatomic, copy) NSString * _Nonnull currentTxProfile;
@end


@interface Profile (SWIFT_EXTENSION(xLib6000))
@end

@class Transmit;
@class Wan;
@class Waveform;
@class Tnf;

SWIFT_CLASS("_TtC8xLib60005Radio")
@interface Radio : NSObject
@property (nonatomic) BOOL pingerEnabled;
@property (nonatomic, readonly) NSInteger uptime;
@property (nonatomic, readonly, copy) NSString * _Nonnull radioVersion;
@property (nonatomic, readonly, strong) Atu * _Null_unspecified atu;
@property (nonatomic, readonly, strong) Cwx * _Null_unspecified cwx;
@property (nonatomic, readonly, strong) Gps * _Null_unspecified gps;
@property (nonatomic, readonly, strong) Interlock * _Null_unspecified interlock;
@property (nonatomic, readonly, strong) Profile * _Null_unspecified profile;
@property (nonatomic, readonly, strong) Transmit * _Null_unspecified transmit;
@property (nonatomic, readonly, strong) Wan * _Null_unspecified wan;
@property (nonatomic, readonly, strong) Waveform * _Null_unspecified waveform;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull antennaList;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull micList;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull rfGainList;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull sliceList;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull sliceErrors;
@property (nonatomic, readonly) NSInteger radioApiVersionMajor;
@property (nonatomic, readonly) NSInteger radioApiVersionMinor;
@property (nonatomic, readonly, copy) NSString * _Nonnull kApiFirmwareSupport;
/// Disconnect the Radio
- (void)disconnect;
/// Find the active Panadapter
///
/// returns:
/// a reference to a Panadapter (or nil)
- (Panadapter * _Nullable)findActivePanadapter SWIFT_WARN_UNUSED_RESULT;
/// Find the Panadapter for a DaxIqChannel
/// \param daxIqChannel a Dax channel number
///
///
/// returns:
/// a Panadapter reference (or nil)
- (Panadapter * _Nullable)findPanadapterByDaxIqChannel:(NSInteger)daxIqChannel SWIFT_WARN_UNUSED_RESULT;
/// Find the IQ Stream for a DaxIqChannel
/// \param daxIqChannel a Dax IQ channel number
///
///
/// returns:
/// an IQ Stream reference (or nil)
- (IqStream * _Nullable)findIqStreamByDaxIqChannel:(NSInteger)daxIqChannel SWIFT_WARN_UNUSED_RESULT;
/// Disable all TxEnabled
- (void)disableTx;
/// Return references to all Slices on the specified Panadapter
/// \param pan a Panadapter Id
///
///
/// returns:
/// an array of Slices (may be empty)
- (NSArray<Slice *> * _Nonnull)findSlicesOn:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
/// Given a Frequency, return the Slice on the specified Panadapter containing it (if any)
/// \param pan a reference to A Panadapter
///
/// \param freq a Frequency (in hz)
///
///
/// returns:
/// a reference to a Slice (or nil)
- (Slice * _Nullable)findSliceOn:(NSString * _Nonnull)id byFrequency:(NSInteger)freq panafallBandwidth:(NSInteger)panafallBandwidth SWIFT_WARN_UNUSED_RESULT;
/// Return the Active Slice on the specified Panadapter (if any)
/// \param pan a Panadapter reference
///
///
/// returns:
/// a Slice reference (or nil)
- (Slice * _Nullable)findActiveSliceOn:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
/// <#Description#>
/// \param channel Dax channel number
///
///
/// returns:
/// a Slice (if any)
- (Slice * _Nullable)findSliceByDaxChannel:(NSInteger)channel SWIFT_WARN_UNUSED_RESULT;
/// Given a Frequency, return a reference to the Tnf containing it (if any)
/// \param freq a Frequency (in hz)
///
///
/// returns:
/// a Tnf reference (or nil)
- (Tnf * _Nullable)findTnfByFrequency:(NSInteger)freq panafallBandwidth:(NSInteger)panafallBandwidth SWIFT_WARN_UNUSED_RESULT;
/// Process the Reply to a command, reply format: <value>,<value>,…<value>
/// \param command the original command
///
/// \param seqNum the Sequence Number of the original command
///
/// \param responseValue the response value
///
/// \param reply the reply
///
- (void)replyHandler:(NSString * _Nonnull)command seqNum:(NSString * _Nonnull)seqNum responseValue:(NSString * _Nonnull)responseValue reply:(NSString * _Nonnull)reply;
/// Process a sent message
/// \param text text of the message
///
- (void)sentMessage:(NSString * _Nonnull)text;
/// Process a received message
/// \param text text of the message
///
- (void)receivedMessage:(NSString * _Nonnull)text;
/// Respond to a TCP Connection/Disconnection event
/// \param connected state of connection
///
/// \param host host address
///
/// \param port port number
///
/// \param error error message
///
- (void)tcpStateWithConnected:(BOOL)connected host:(NSString * _Nonnull)host port:(uint16_t)port error:(NSString * _Nonnull)error;
/// Receive an Error message from TCP Manager
/// \param message the error message
///
- (void)tcpError:(NSString * _Nonnull)message;
/// Respond to a UDP Connection/Disconnection event
/// \param bound state of binding
///
/// \param port a port number
///
/// \param error error message
///
- (void)udpStateWithBound:(BOOL)bound port:(uint16_t)port error:(NSString * _Nonnull)error;
/// Receive a State Change message from UDP Manager
/// \param active the state
///
- (void)udpStreamWithActive:(BOOL)active;
/// Receive an Error message from UDP Manager
/// \param message error message
///
- (void)udpError:(NSString * _Nonnull)message;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface Radio (SWIFT_EXTENSION(xLib6000))
/// Send a command to the Radio (hardware)
/// \param command a Command String
///
/// \param flag use “D”iagnostic form
///
/// \param callback a callback function (if any)
///
- (void)send:(NSString * _Nonnull)command diagnostic:(BOOL)flag replyTo:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Send a command to the Radio (hardware), first check that a Radio is connected
/// \param command a Command String
///
/// \param flag use “D”iagnostic form
///
/// \param callback a callback function (if any)
///
///
/// returns:
/// Success / Failure
- (BOOL)sendWithCheck:(NSString * _Nonnull)command diagnostic:(BOOL)flag replyTo:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback SWIFT_WARN_UNUSED_RESULT;
/// Send a Vita packet to the Radio
/// \param data a Vita-49 packet as Data
///
- (void)sendVitaData:(NSData * _Nullable)data;
/// Request a list of antenns
- (void)antennaListRequestWithCallback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Clear the ATU
- (void)atuClearWithCallback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Start the ATU
- (void)atuStartWithCallback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Bypass the ATU
- (void)atuBypassWithCallback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Create an Audio Stream
/// \param channel DAX channel number
///
/// \param callback ReplyHandler (optional)
///
///
/// returns:
/// Success / Failure
- (BOOL)audioStreamCreate:(NSString * _Nonnull)channel callback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback SWIFT_WARN_UNUSED_RESULT;
/// Remove an Audio Stream
/// \param id Audio Stream Id
///
///
/// returns:
/// Success / Failure
- (BOOL)audioStreamRemove:(NSString * _Nonnull)id callback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback SWIFT_WARN_UNUSED_RESULT;
/// Create an IQ Stream
/// \param channel DAX channel number
///
/// \param callback ReplyHandler (optional)
///
///
/// returns:
/// Success / Failure
- (BOOL)iqStreamCreate:(NSString * _Nonnull)channel callback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback SWIFT_WARN_UNUSED_RESULT;
/// Create an IQ Stream
/// \param channel DAX channel number
///
/// \param ip ip address
///
/// \param port port number
///
/// \param callback ReplyHandler (optional)
///
///
/// returns:
/// Success / Failure
- (BOOL)iqStreamCreate:(NSString * _Nonnull)channel ip:(NSString * _Nonnull)ip port:(NSInteger)port callback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback SWIFT_WARN_UNUSED_RESULT;
/// Remove an IQ Stream
/// \param id IQ Stream Id
///
- (void)iqStreamRemove:(NSString * _Nonnull)id callback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Create a Memory
- (void)memoryCreateWithCallback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Remove a Memory
/// \param id Memory Id
///
- (void)memoryRemove:(NSString * _Nonnull)id callback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Request a list of Meters
- (void)meterListRequestWithCallback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Create a Mic Audio Stream
/// \param callback ReplyHandler (optional)
///
///
/// returns:
/// Success / Failure
- (BOOL)micAudioStreamCreateWithCallback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback SWIFT_WARN_UNUSED_RESULT;
/// Remove a Mic Audio Stream
/// \param id Mic Audio Stream Id
///
- (void)micAudioStreamRemove:(NSString * _Nonnull)id callback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Request a List of Mic sources
- (void)micListRequestWithCallback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Create a Panafall
/// \param dimensions Panafall dimensions
///
- (void)panafallCreate:(CGSize)dimensions callback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Remove a Panafall
/// \param id Panafall Id
///
- (void)panafallRemove:(NSString * _Nonnull)id callback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Delete a Global profile
/// \param name profile name
///
- (void)profileGlobalDelete:(NSString * _Nonnull)name callback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Save a Global profile
/// \param name profile name
///
- (void)profileGlobalSave:(NSString * _Nonnull)name callback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Delete a Mic profile
/// \param name profile name
///
- (void)profileMicDelete:(NSString * _Nonnull)name callback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Save a Mic profile
/// \param name profile name
///
- (void)profileMicSave:(NSString * _Nonnull)name callback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Delete a Transmit profile
/// \param name profile name
///
- (void)profileTransmitDelete:(NSString * _Nonnull)name callback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Save a Transmit profile
/// \param name profile name
///
- (void)profileTransmitSave:(NSString * _Nonnull)name callback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Turn Opus Rx On/Off
/// \param value On/Off
///
- (void)remoteRxAudioRequest:(BOOL)value callback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
- (void)remoteTxAudioRequest:(BOOL)value callback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Reboot the Radio
- (void)rebootRequestWithCallback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Create a new Slice
/// \param frequency frequenct (Hz)
///
/// \param antenna selected antenna
///
/// \param mode selected mode
///
- (void)sliceCreateWithFrequency:(NSInteger)frequency antenna:(NSString * _Nonnull)antenna mode:(NSString * _Nonnull)mode callback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Create a new Slice
/// \param panadapter selected panadapter
///
/// \param frequency frequency (Hz)
///
- (void)sliceCreateWithPanadapter:(Panadapter * _Nonnull)panadapter frequency:(NSInteger)frequency callback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Remove a Slice
/// \param id Slice Id
///
- (void)sliceRemove:(NSString * _Nonnull)id callback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// <#Description#>
/// \param id <#id description#>
///
- (void)sliceErrorRequest:(NSString * _Nonnull)id callback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Request a list of slice Stream Id’s
- (void)sliceListRequestWithCallback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Create a Tnf
/// \param frequency frequency (Hz)
///
/// \param panadapter Panadapter Id
///
- (void)tnfCreateWithFrequency:(NSInteger)frequency panadapter:(Panadapter * _Nonnull)panadapter callback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Remove a Tnf
/// \param tnf Tnf Id
///
- (void)tnfRemoveWithTnf:(Tnf * _Nonnull)tnf callback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Turn MOX On/Off
/// \param value On/Off
///
- (void)transmitSet:(BOOL)value callback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Create a Tx Audio Stream
/// \param callback ReplyHandler (optional)
///
///
/// returns:
/// Success / Failure
- (BOOL)txAudioStreamCreateWithCallback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback SWIFT_WARN_UNUSED_RESULT;
/// Remove a Tx Audio Stream
/// \param id TxAudioStream Id
///
- (void)txAudioStreamRemove:(NSString * _Nonnull)id callback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Request the elapsed uptime
- (void)uptimeRequestWithCallback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
/// Remove a UsbCable
/// \param id UsbCable serial number
///
/// \param callback ReplyHandler (optional)
///
///
/// returns:
/// Success / Failure
- (BOOL)usbCableRemove:(NSString * _Nonnull)id callback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback SWIFT_WARN_UNUSED_RESULT;
/// Create an Xvtr
/// \param callback ReplyHandler (optional)
///
///
/// returns:
/// Success / Failure
- (BOOL)xvtrCreateWithCallback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback SWIFT_WARN_UNUSED_RESULT;
/// Remove an Xvtr
/// \param id Xvtr Id
///
- (void)xvtrRemove:(NSString * _Nonnull)id callback:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback;
@property (nonatomic) BOOL apfEnabled;
@property (nonatomic) NSInteger apfQFactor;
@property (nonatomic) NSInteger apfGain;
@property (nonatomic) BOOL bandPersistenceEnabled;
@property (nonatomic) BOOL binauralRxEnabled;
@property (nonatomic) NSInteger calFreq;
@property (nonatomic, copy) NSString * _Nonnull callsign;
@property (nonatomic) BOOL enforcePrivateIpEnabled;
@property (nonatomic) NSInteger filterCwAutoLevel;
@property (nonatomic) NSInteger filterDigitalAutoLevel;
@property (nonatomic) NSInteger filterVoiceAutoLevel;
@property (nonatomic) NSInteger filterCwLevel;
@property (nonatomic) NSInteger filterDigitalLevel;
@property (nonatomic) NSInteger filterVoiceLevel;
@property (nonatomic) NSInteger freqErrorPpb;
@property (nonatomic) BOOL fullDuplexEnabled;
@property (nonatomic) NSInteger headphoneGain;
@property (nonatomic) BOOL headphoneMute;
@property (nonatomic) NSInteger lineoutGain;
@property (nonatomic) BOOL lineoutMute;
@property (nonatomic, copy) NSString * _Nonnull nickname;
@property (nonatomic, copy) NSString * _Nonnull radioScreenSaver;
@property (nonatomic) BOOL remoteOnEnabled;
@property (nonatomic) NSInteger rttyMark;
@property (nonatomic) BOOL snapTuneEnabled;
@property (nonatomic) BOOL startOffset;
@property (nonatomic, copy) NSString * _Nonnull staticGateway;
@property (nonatomic, copy) NSString * _Nonnull staticIp;
@property (nonatomic, copy) NSString * _Nonnull staticNetmask;
@property (nonatomic) BOOL tnfEnabled;
@end

@class TxAudioStream;
@class Waterfall;
@class UsbCable;
@class Xvtr;

@interface Radio (SWIFT_EXTENSION(xLib6000))
@property (nonatomic, readonly) NSInteger availablePanadapters;
@property (nonatomic, readonly) NSInteger availableSlices;
@property (nonatomic, readonly, copy) NSString * _Nonnull chassisSerial;
@property (nonatomic, readonly) NSInteger daxIqAvailable;
@property (nonatomic, readonly) NSInteger daxIqCapacity;
@property (nonatomic, readonly, copy) NSString * _Nonnull fpgaMbVersion;
@property (nonatomic, readonly, copy) NSString * _Nonnull gateway;
@property (nonatomic, readonly, copy) NSString * _Nonnull ipAddress;
@property (nonatomic, readonly, copy) NSString * _Nonnull location;
@property (nonatomic, readonly, copy) NSString * _Nonnull macAddress;
@property (nonatomic, readonly, copy) NSString * _Nonnull netmask;
@property (nonatomic, readonly) NSInteger numberOfScus;
@property (nonatomic, readonly) NSInteger numberOfSlices;
@property (nonatomic, readonly) NSInteger numberOfTx;
@property (nonatomic, readonly, copy) NSString * _Nonnull psocMbPa100Version;
@property (nonatomic, readonly, copy) NSString * _Nonnull psocMbtrxVersion;
@property (nonatomic, readonly, copy) NSString * _Nonnull radioModel;
@property (nonatomic, readonly, copy) NSString * _Nonnull radioOptions;
@property (nonatomic, readonly, copy) NSString * _Nonnull region;
@property (nonatomic, readonly, copy) NSString * _Nonnull smartSdrMB;
@property (nonatomic, readonly, copy) NSString * _Nonnull softwareVersion;
@property (nonatomic, copy) NSDictionary<NSString *, Amplifier *> * _Nonnull amplifiers;
@property (nonatomic, copy) NSDictionary<NSString *, AudioStream *> * _Nonnull audioStreams;
@property (nonatomic, copy) NSDictionary<NSString *, IqStream *> * _Nonnull iqStreams;
@property (nonatomic, copy) NSDictionary<NSString *, Memory *> * _Nonnull memories;
@property (nonatomic, copy) NSDictionary<NSString *, MicAudioStream *> * _Nonnull micAudioStreams;
@property (nonatomic, copy) NSDictionary<NSString *, Opus *> * _Nonnull opusStreams;
@property (nonatomic, copy) NSDictionary<NSString *, Panadapter *> * _Nonnull panadapters;
@property (nonatomic, copy) NSDictionary<NSString *, Slice *> * _Nonnull slices;
@property (nonatomic, copy) NSDictionary<NSString *, Tnf *> * _Nonnull tnfs;
@property (nonatomic, copy) NSDictionary<NSString *, TxAudioStream *> * _Nonnull txAudioStreams;
@property (nonatomic, copy) NSDictionary<NSString *, Waterfall *> * _Nonnull waterfalls;
@property (nonatomic, copy) NSDictionary<NSString *, UsbCable *> * _Nonnull usbCables;
@property (nonatomic, copy) NSDictionary<NSString *, Xvtr *> * _Nonnull xvtrs;
@property (nonatomic) uint16_t _udpPort;
@end

@class GCDAsyncUdpSocket;

SWIFT_CLASS("_TtC8xLib600012RadioFactory")
@interface RadioFactory : NSObject <GCDAsyncUdpSocketDelegate>
/// Initialize a RadioFactory
/// \param discoveryPort port number
///
/// \param checkInterval how often to check
///
/// \param notSeenInterval timeout interval
///
- (nonnull instancetype)initWithDiscoveryPort:(uint16_t)discoveryPort checkInterval:(NSTimeInterval)checkInterval notSeenInterval:(NSTimeInterval)notSeenInterval OBJC_DESIGNATED_INITIALIZER;
/// send a Notification containing a list of current radios
- (void)updateAvailableRadios;
/// The Socket received data
/// \param sock the GCDAsyncUdpSocket
///
/// \param data the Data received
///
/// \param address the Address of the sender
///
/// \param filterContext the FilterContext
///
- (void)udpSocket:(GCDAsyncUdpSocket * _Nonnull)sock didReceiveData:(NSData * _Nonnull)data fromAddress:(NSData * _Nonnull)address withFilterContext:(id _Nullable)filterContext;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC8xLib60005Slice")
@interface Slice : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
/// Initialize a Slice
/// \param radio parent Radio class
///
/// \param sliceId a Slice Id
///
/// \param queue Slice concurrent queue
///
- (nonnull instancetype)initWithRadio:(Radio * _Nonnull)radio sliceId:(NSString * _Nonnull)sliceId queue:(dispatch_queue_t _Nonnull)queue OBJC_DESIGNATED_INITIALIZER;
- (void)setRecord:(BOOL)value;
- (void)setPlay:(BOOL)value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface Slice (SWIFT_EXTENSION(xLib6000))
@property (nonatomic) BOOL active;
@property (nonatomic, copy) NSString * _Nonnull agcMode;
@property (nonatomic) NSInteger agcOffLevel;
@property (nonatomic) NSInteger agcThreshold;
@property (nonatomic) BOOL anfEnabled;
@property (nonatomic) NSInteger anfLevel;
@property (nonatomic) BOOL apfEnabled;
@property (nonatomic) NSInteger apfLevel;
@property (nonatomic) NSInteger audioGain;
@property (nonatomic) BOOL audioMute;
@property (nonatomic) NSInteger audioPan;
@property (nonatomic) NSInteger daxChannel;
@property (nonatomic) BOOL dfmPreDeEmphasisEnabled;
@property (nonatomic) NSInteger digitalLowerOffset;
@property (nonatomic) NSInteger digitalUpperOffset;
@property (nonatomic) BOOL diversityEnabled;
@property (nonatomic) NSInteger filterHigh;
@property (nonatomic) NSInteger filterLow;
@property (nonatomic) NSInteger fmDeviation;
@property (nonatomic) float fmRepeaterOffset;
@property (nonatomic) BOOL fmToneBurstEnabled;
@property (nonatomic) float fmToneFreq;
@property (nonatomic, copy) NSString * _Nonnull fmToneMode;
@property (nonatomic) NSInteger frequency;
@property (nonatomic) BOOL locked;
@property (nonatomic) BOOL loopAEnabled;
@property (nonatomic) BOOL loopBEnabled;
@property (nonatomic, copy) NSString * _Nonnull mode;
@property (nonatomic) BOOL nbEnabled;
@property (nonatomic) NSInteger nbLevel;
@property (nonatomic) BOOL nrEnabled;
@property (nonatomic) NSInteger nrLevel;
@property (nonatomic) BOOL playbackEnabled;
@property (nonatomic) BOOL recordEnabled;
@property (nonatomic, copy) NSString * _Nonnull repeaterOffsetDirection;
@property (nonatomic) NSInteger rfGain;
@property (nonatomic) BOOL ritEnabled;
@property (nonatomic) NSInteger ritOffset;
@property (nonatomic) NSInteger rttyMark;
@property (nonatomic) NSInteger rttyShift;
@property (nonatomic, copy) NSString * _Nonnull rxAnt;
@property (nonatomic) NSInteger step;
@property (nonatomic, copy) NSString * _Nonnull stepList;
@property (nonatomic) BOOL squelchEnabled;
@property (nonatomic) NSInteger squelchLevel;
@property (nonatomic, copy) NSString * _Nonnull txAnt;
@property (nonatomic) BOOL txEnabled;
@property (nonatomic) float txOffsetFreq;
@property (nonatomic) BOOL wnbEnabled;
@property (nonatomic) NSInteger wnbLevel;
@property (nonatomic) BOOL xitEnabled;
@property (nonatomic) NSInteger xitOffset;
@end


@interface Slice (SWIFT_EXTENSION(xLib6000))
@property (nonatomic) NSInteger daxClients;
@property (nonatomic) BOOL daxTxEnabled;
@property (nonatomic) BOOL diversityChild;
@property (nonatomic) NSInteger diversityIndex;
@property (nonatomic) BOOL diversityParent;
@property (nonatomic, readonly) BOOL inUse;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull modeList;
@property (nonatomic) NSInteger owner;
@property (nonatomic, copy) NSString * _Nonnull panadapterId;
@property (nonatomic) BOOL postDemodBypassEnabled;
@property (nonatomic) NSInteger postDemodHigh;
@property (nonatomic) NSInteger postDemodLow;
@property (nonatomic) BOOL qskEnabled;
@property (nonatomic) float recordLength;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull rxAntList;
@property (nonatomic) BOOL wide;
@end

@class GCDAsyncSocket;

SWIFT_CLASS("_TtC8xLib600010TcpManager")
@interface TcpManager : NSObject <GCDAsyncSocketDelegate>
@property (nonatomic, readonly) BOOL isConnected;
/// Disconnect from the Radio (hardware)
- (void)disconnect;
/// Send a Command to the Radio (hardware), optionally register to be Notified upon receipt of a Reply
/// \param cmd a Command string
///
/// \param diagnostic whether to add “D” suffix
///
/// \param replyTo ReplyHandler (if any)
///
///
/// returns:
/// the Sequence Number of the Command
- (NSInteger)send:(NSString * _Nonnull)cmd diagnostic:(BOOL)diagnostic replyTo:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))callback SWIFT_WARN_UNUSED_RESULT;
/// Read the next data block (with an indefinite timeout)
- (void)readNext;
/// Called when the TCP/IP connection has been disconnected
/// \param sock the disconnected socket
///
/// \param err the error
///
- (void)socketDidDisconnect:(GCDAsyncSocket * _Nonnull)sock withError:(NSError * _Nullable)err;
/// Called after the TCP/IP connection has been established
/// \param sock the socket
///
/// \param host the host
///
/// \param port the port
///
- (void)socket:(GCDAsyncSocket * _Nonnull)sock didConnectToHost:(NSString * _Nonnull)host port:(uint16_t)port;
/// Called when data has been read from the TCP/IP connection
/// \param sock the socket data was received on
///
/// \param data the Data
///
/// \param tag the Tag associated with this receipt
///
- (void)socket:(GCDAsyncSocket * _Nonnull)sock didReadData:(NSData * _Nonnull)data withTag:(NSInteger)tag;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC8xLib60003Tnf")
@interface Tnf : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic) NSInteger minWidth;
@property (nonatomic) NSInteger maxWidth;
/// Initialize a Tnf
/// \param id a Tnf Id
///
/// \param radio parent Radio class
///
/// \param queue Tnf Concurrent queue
///
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id radio:(Radio * _Nonnull)radio queue:(dispatch_queue_t _Nonnull)queue;
/// Initialize a Tnf
/// \param id a Tnf Id
///
/// \param radio parent Radio class
///
/// \param frequency Tnf frequency (Hz)
///
/// \param queue Tnf Concurrent queue
///
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id radio:(Radio * _Nonnull)radio frequency:(NSInteger)frequency queue:(dispatch_queue_t _Nonnull)queue;
/// Initialize a Tnf
/// \param id a Tnf Id
///
/// \param radio parent Radio class
///
/// \param frequency Tnf frequency (Hz)
///
/// \param depth a Depth value
///
/// \param width a Width value
///
/// \param permanent true = permanent
///
/// \param queue Tnf Concurrent queue
///
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id radio:(Radio * _Nonnull)radio frequency:(NSInteger)frequency depth:(NSInteger)depth width:(NSInteger)width permanent:(BOOL)permanent queue:(dispatch_queue_t _Nonnull)queue OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface Tnf (SWIFT_EXTENSION(xLib6000))
@end


@interface Tnf (SWIFT_EXTENSION(xLib6000))
@property (nonatomic) NSInteger depth;
@property (nonatomic) NSInteger frequency;
@property (nonatomic) BOOL permanent;
@property (nonatomic) NSInteger width;
@end


SWIFT_CLASS("_TtC8xLib60008Transmit")
@interface Transmit : NSObject
- (nonnull instancetype)initWithRadio:(Radio * _Nonnull)radio queue:(dispatch_queue_t _Nonnull)queue OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface Transmit (SWIFT_EXTENSION(xLib6000))
@property (nonatomic) NSInteger carrierLevel;
@property (nonatomic) BOOL companderEnabled;
@property (nonatomic) NSInteger companderLevel;
@property (nonatomic) BOOL cwAutoSpaceEnabled;
@property (nonatomic) NSInteger cwBreakInDelay;
@property (nonatomic) BOOL cwBreakInEnabled;
@property (nonatomic) BOOL cwIambicEnabled;
@property (nonatomic) NSInteger cwIambicMode;
@property (nonatomic) BOOL cwlEnabled;
@property (nonatomic) NSInteger cwPitch;
@property (nonatomic) BOOL cwSidetoneEnabled;
@property (nonatomic) NSInteger cwSpeed;
@property (nonatomic) BOOL cwSwapPaddles;
@property (nonatomic) BOOL cwSyncCwxEnabled;
@property (nonatomic) NSInteger cwWeight;
@property (nonatomic) BOOL daxEnabled;
@property (nonatomic) BOOL hwAlcEnabled;
@property (nonatomic) BOOL inhibit;
@property (nonatomic) NSInteger maxPowerLevel;
@property (nonatomic) BOOL metInRxEnabled;
@property (nonatomic) BOOL micAccEnabled;
@property (nonatomic) BOOL micBiasEnabled;
@property (nonatomic) BOOL micBoostEnabled;
@property (nonatomic) NSInteger micLevel;
@property (nonatomic, copy) NSString * _Nonnull micSelection;
@property (nonatomic) NSInteger rfPower;
@property (nonatomic) BOOL speechProcessorEnabled;
@property (nonatomic) NSInteger speechProcessorLevel;
@property (nonatomic) BOOL ssbPeakControlEnabled;
@property (nonatomic) BOOL tune;
@property (nonatomic) NSInteger tunePower;
@property (nonatomic) NSInteger txFilterHigh;
@property (nonatomic) NSInteger txFilterLow;
@property (nonatomic) BOOL txInWaterfallEnabled;
@property (nonatomic) BOOL txMonitorEnabled;
@property (nonatomic) NSInteger txMonitorGainCw;
@property (nonatomic) NSInteger txMonitorGainSb;
@property (nonatomic) NSInteger txMonitorPanCw;
@property (nonatomic) NSInteger txMonitorPanSb;
@property (nonatomic) BOOL voxEnabled;
@property (nonatomic) NSInteger voxDelay;
@property (nonatomic) NSInteger voxLevel;
@end


@interface Transmit (SWIFT_EXTENSION(xLib6000))
@property (nonatomic) NSInteger frequency;
@property (nonatomic, readonly) BOOL rawIqEnabled;
@property (nonatomic, readonly) BOOL txFilterChanges;
@property (nonatomic, readonly) BOOL txMonitorAvailable;
@property (nonatomic, readonly) BOOL txRfPowerChanges;
@end


SWIFT_CLASS("_TtC8xLib600013TxAudioStream")
@interface TxAudioStream : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
- (BOOL)sendTXAudioWithLeft:(NSArray<NSNumber *> * _Nonnull)left right:(NSArray<NSNumber *> * _Nonnull)right samples:(NSInteger)samples SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface TxAudioStream (SWIFT_EXTENSION(xLib6000))
@property (nonatomic) BOOL transmit;
@end


@interface TxAudioStream (SWIFT_EXTENSION(xLib6000))
@property (nonatomic, readonly) BOOL inUse;
@property (nonatomic, copy) NSString * _Nonnull ip;
@property (nonatomic) NSInteger port;
@property (nonatomic) NSInteger txGain;
@end


SWIFT_CLASS("_TtC8xLib600010UdpManager")
@interface UdpManager : NSObject <GCDAsyncUdpSocketDelegate>
@property (nonatomic, readonly) uint16_t port;
@property (nonatomic, readonly) BOOL canBroadcast;
/// Send a Broadcast
/// \param data a Vita-49 packet as Data
///
- (void)sendBroadcastWithData:(NSData * _Nonnull)data;
/// Send Vita packet to radio
/// \param data a Vita-49 packet as Data
///
- (void)sendData:(NSData * _Nonnull)data;
- (void)beginReceiving;
/// Unbind from the UDP port
- (void)unbind;
/// Called when data has been read from the UDP connection
/// \param sock the receiving socket
///
/// \param data the data received
///
/// \param address the Host address
///
/// \param filterContext a filter context (if any)
///
- (void)udpSocket:(GCDAsyncUdpSocket * _Nonnull)sock didReceiveData:(NSData * _Nonnull)data fromAddress:(NSData * _Nonnull)address withFilterContext:(id _Nullable)filterContext;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC8xLib60008UsbCable")
@interface UsbCable : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface UsbCable (SWIFT_EXTENSION(xLib6000))
@property (nonatomic) BOOL autoReport;
@property (nonatomic, copy) NSString * _Nonnull band;
@property (nonatomic) NSInteger dataBits;
@property (nonatomic) BOOL enable;
@property (nonatomic, copy) NSString * _Nonnull flowControl;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull parity;
@property (nonatomic) BOOL pluggedIn;
@property (nonatomic, copy) NSString * _Nonnull polarity;
@property (nonatomic, copy) NSString * _Nonnull preamp;
@property (nonatomic, copy) NSString * _Nonnull source;
@property (nonatomic, copy) NSString * _Nonnull sourceRxAnt;
@property (nonatomic) NSInteger sourceSlice;
@property (nonatomic, copy) NSString * _Nonnull sourceTxAnt;
@property (nonatomic) NSInteger speed;
@property (nonatomic) NSInteger stopBits;
@property (nonatomic) BOOL usbLog;
@end


@interface UsbCable (SWIFT_EXTENSION(xLib6000))
@end


SWIFT_CLASS("_TtC8xLib60003Wan")
@interface Wan : NSObject
- (nonnull instancetype)initWithRadio:(Radio * _Nonnull)radio queue:(dispatch_queue_t _Nonnull)queue OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface Wan (SWIFT_EXTENSION(xLib6000))
@property (nonatomic, readonly) BOOL radioAuthenticated;
@property (nonatomic, readonly) BOOL serverConnected;
@end


SWIFT_CLASS("_TtC8xLib60009Waterfall")
@interface Waterfall : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly) NSInteger lastTimecode;
@property (nonatomic, readonly) NSInteger droppedPackets;
@property (nonatomic, readonly) BOOL isBeingRemoved;
/// Initialize a Waterfall
/// \param streamId a Waterfall Id
///
/// \param radio parent Radio class
///
/// \param queue Waterfall Concurrent queue
///
- (nonnull instancetype)initWithStreamId:(NSString * _Nonnull)streamId radio:(Radio * _Nonnull)radio queue:(dispatch_queue_t _Nonnull)queue OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface Waterfall (SWIFT_EXTENSION(xLib6000))
@property (nonatomic) BOOL autoBlackEnabled;
@property (nonatomic) NSInteger blackLevel;
@property (nonatomic) NSInteger colorGain;
@property (nonatomic) NSInteger gradientIndex;
@property (nonatomic) NSInteger lineDuration;
@end


@interface Waterfall (SWIFT_EXTENSION(xLib6000))
@property (nonatomic, readonly) uint32_t autoBlackLevel;
@property (nonatomic, readonly, copy) NSString * _Nonnull panadapterId;
@end


SWIFT_CLASS("_TtC8xLib60008Waveform")
@interface Waveform : NSObject
- (nonnull instancetype)initWithRadio:(Radio * _Nonnull)radio queue:(dispatch_queue_t _Nonnull)queue OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface Waveform (SWIFT_EXTENSION(xLib6000))
@property (nonatomic, readonly, copy) NSString * _Nonnull waveformList;
@end


SWIFT_CLASS("_TtC8xLib60004Xvtr")
@interface Xvtr : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
/// Initialize an Xvtr
/// \param id an Xvtr Id
///
/// \param radio parent Radio class
///
/// \param queue Xvtr Concurrent queue
///
- (nonnull instancetype)initWithRadio:(Radio * _Nonnull)radio id:(NSString * _Nonnull)id queue:(dispatch_queue_t _Nonnull)queue OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface Xvtr (SWIFT_EXTENSION(xLib6000))
@property (nonatomic) NSInteger ifFrequency;
@property (nonatomic) NSInteger loError;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) NSInteger maxPower;
@property (nonatomic) NSInteger order;
@property (nonatomic) NSInteger rfFrequency;
@property (nonatomic) NSInteger rxGain;
@property (nonatomic) BOOL rxOnly;
@end


@interface Xvtr (SWIFT_EXTENSION(xLib6000))
@property (nonatomic, readonly) BOOL inUse;
@property (nonatomic, readonly) BOOL isValid;
@property (nonatomic, readonly) BOOL preferred;
@property (nonatomic, readonly) NSInteger twoMeterInt;
@end

#pragma clang diagnostic pop
